project: 'hens'
mode: 'base' # 'base' 'cyclone_tracking' 'diagnostic'
# random_seed: 377777

start_times: ["2020-01-01"]
# ic_block_start: "2020-01-08"
# ic_block_end: "2020-01-09"
ic_block_step: 24

nsteps: 2          # number of forecasting steps
nensemble: 2       # ensemble size per checkpoint
batch_size: 2      # inference batch size

forecast_model:
    architecture: earth2studio.models.px.SFNO   # forecast model class
    #package: '/model_registry'         # path to directory with model packages, comment for default
    max_num_checkpoints: 29                      # max number of checkpoints which will be used

diagnostic_model:
    architecture: earth2studio.models.dx.PrecipitationAFNO

cyclone_tracking:
    out_dir: './outputs'       # path to which write cyclone tracks

perturbation:
    method: 'hcbv'             # perturbation method
    perturbed_var: 'z500'      # variable perurbed in seed perturbation
    noise_amplification: .35   # amplification of noise
    integration_steps: 3
    skill_path: '/code/gitlab_nvidia/earth2studio-aie/d2m_sfno_linear_74chq_sc2_layers8_edim620_wstgl2-epoch70_seed16.nc'
    #method: 'bv'             # perturbation method
    #integration_steps: 3       # integration steps in vector breeding
    #noise_amplification: .35   # amplification of noise

data_source:
    _target_: earth2studio.data.ARCO  # data source class

file_output:
    path: './outputs'       # directory to which outfiles are written
    output_vars: ["t2m", 'u10m', 't850', 'q850', 'z500']
    thread_io: False      # write out in seperate thread (needs further testing)
    format:               # io backend class
        _target_: earth2studio.io.KVBackend
        # _target_: earth2studio.io.XarrayBackend
    cropbox:
        lat_min: -60
        lat_max: 60
        lon_min: 0
        lon_max: 360


    # format:
    #     _target_: earth2studio.io.NetCDF4Backend
    #     _partial_: True
    #     backend_kwargs:
    #         mode: 'w'
    #         diskless: False
    #         persist: False
    #         chunks:
    #             ensemble: 1
    #             time: 1
    #             lead_time: 1

    # format:
    #     _target_: earth2studio.io.ZarrBackend
    #     _partial_: True
    #     chunks:
    #         ensemble: 1
    #         time: 1
    #         lead_time: 1
    #     backend_kwargs:
    #         overwrite: True
